### ISSUE TITLE
unable to import load_data

### ISSUE THREAD

**Issue by rbenel** [RomGutman/MLHC_db_connection#1]
After installing all of the necessary libraries and downloading the MLHC file, and changing the parameters of the config file, I am unable to import load_data.

Python Version 3.6
Ubuntu 18.04

```
Traceback (most recent call last):
  File "/home/machineLearning/get_data.py", line 1, in <module>
    from load_data import LoadData
  File "/home/machineLearning/load_data.py", line 5, in <module>
    import pandas as pd
  File "/home/.local/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
```

**Comment by RomGutman** [comment]
Hi @rbenel , 

Can you please try to run `import numpy as np` on the same environment and see if you got any errors?
From searching online, the problem seems to be with related to it

**Comment by rbenel** [comment]
Hi @RomGutman, 
I uninstalled all versions of numpy and reinstalled numpy-1.16.2, and I still receive the same error as before..

**Comment by rbenel** [comment]
Hi @RomGutman,
So the issue was with pandas.. the first example in the tutorial works, but not the second.. I will continue debugging. 
Thanks

**Comment by rbenel** [comment]
Hi @RomGutman, 
It seems it was an anaconda issue :( 

Thanks!
